# Generated by Django 4.1.1 on 2022-10-08 00:31

import construyeapp.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAgencia', models.CharField(max_length=150, unique=True, validators=[construyeapp.validators.validar_texto])),
                ('direccionAgencia', models.CharField(max_length=150, validators=[construyeapp.validators.validar_texto])),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'permissions': [('reporte_cantidad', 'Visualizar el reporte de cantidad'), ('reporte_detalle', 'Reporte detallado de cantidades')],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidades', models.CharField(choices=[('ud', 'Unidades'), ('kg', 'Kilogramo'), ('ton', 'Tonelada')], default='ud', max_length=5)),
                ('disponible', models.BooleanField(blank=True, default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construyeapp.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEntrega', models.DateField()),
                ('direccionEntrega', models.CharField(max_length=100, validators=[construyeapp.validators.validar_texto])),
                ('precioTotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[construyeapp.validators.validar_positivo])),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construyeapp.agencia')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construyeapp.producto')),
            ],
        ),
    ]
